name: Continous Integration
on:
  push: 
    branches: [ 'master', 'dev' ]
    paths:
      - 'force-app/**'
  pull_request: 
    branches: [ 'master', 'dev' ]
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ GitHub.ref }}
          fetch-depth: 0
        if: GitHub.event.action == 'opened' || GitHub.event.action == 'synchronize' || GitHub.event.action == 'push'
      
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core

      - name: Get SFDX Auth URL
        shell: bash
        run: 'echo ${{ secrets.SFDX_AUTH_URL }} > SFDX_AUTH_URL'

      - name: Authorize DevHub
        run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_AUTH_URL -s -a LRQA

      - name: Run Apex Tests
        run: node_modules/sfdx-cli/bin/run force:apex:run:test --resultformat tap --codecoverage -c -r human
